name: Generate Skill Tree

on:
  push:
    paths: ['config/*.json']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generar versión Oscura
      - name: Generate Dark SVG
        uses: Daviz2402/SkillTree@main
        with:
          config-path: 'config/skills.json'
          output-path: 'output/skill-tree.svg'
      # Subir a la rama 'output'
      - name: Deploy to Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
          branch: output
